name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  collect-solutions:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Find Dockerfiles"
        id: "solutions"
        run: |
          SOLUTIONS=$(find Primes* -type f -name Dockerfile -exec dirname {} \; | sort | sed -e 's|^./||' | jq -R '[.]' | jq -s -c -M 'add')
          echo "::set-output name=solutions::${SOLUTIONS}"

    outputs:
      solutions: ${{ steps.solutions.outputs.solutions }}

  build:
    runs-on: "ubuntu-20.04"

    needs: ["collect-solutions"]

    strategy:
      matrix:
        solution: ${{ fromJson(needs.collect-solutions.outputs.solutions) }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build amd64
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.solution }}
          push: false
          platforms: linux/amd64
