name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  collect:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      
      - name: "Find Dockerfiles"
        run: |
          SOLUTIONS=$(find . -type f -name Dockerfile -exec dirname {} \;| sed -e 's|^./||' |jq -R '[.]' | jq -s -c -M 'add')
          echo "::set-output name=solutions::${SOLUTIONS}"

  build:
    runs-on: ubuntu-20.04

    needs: [ "collect" ]

    strategy:
      matrix:
        solution:
          - PrimeCrystal/solution_1
          - PrimeRust/solution_1
        os: ["ubuntu-20.04"]

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Normalize solution name"
        id: solution-name
        run: |
          NAME=$(echo "${{ matrix.solution }}" | sed -r 's/\//_/g' | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=normalized::${NAME}"

      - name: "Build container image"
        run: |
          cd "${{ matrix.solution }}"
          docker build -t "${{ steps.solution-name.outputs.normalized }}" .
